name: Actions Workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: List Files
        run:
          pwd
          ls
      - name: Checkout
      - name: List Files after checkout
        run:
          pwd
          ls -a
        uses: actions/checkout@v1
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Robert
      - name: Log Greeting time
        run: echo "Hello ${{ steps.greet.outputs.time }}"
    
  